In [1]:
import numpy as np

In [7]:
A = np.array([[1,2,4],[2,4,3],[0,1,1]])
B = np.array([[3,5,11],[3,5,2],[1,2,0]])


In [8]:
C = np.arange(0,11,2)
C.reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [13]:
print(np.subtract(A,B))
print(np.add(A,B))
print(np.multiply(A,B))

[[-2 -3 -7]
 [-1 -1  1]
 [-1 -1  1]]
[[ 4  7 15]
 [ 5  9  5]
 [ 1  3  1]]
[[ 3 10 44]
 [ 6 20  6]
 [ 0  2  0]]
